name: Functional Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: scala-jdk11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Regex Test Suites
        uses: paulschuberth/regex-extract-action@v1.0.1
        id: regex-test-suites
        with:
          haystack: ${{ github.event.pull_request.body }}
          needle: '#+ [T|t]est [S|s]uites\n([\S\s]*)\n'
          mode: 'first'
      
      - name: Regex Test Tags
        uses: paulschuberth/regex-extract-action@v1.0.1
        id: regex-test-tags
        with:
          haystack: ${{ steps.regex-test-suites.outputs.group1 }}
          needle: '- \[[xX]\] (.+)'
          mode: all
