name: Actions Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '#+\s*[Tt]est\s*[Ss]uites\s*\n([\S\s]*)\n\s*\n'

      - name: Dump match
        run: |
          echo '${{ steps.regex-match.outputs.match }}'
          echo '${{ steps.regex-match.outputs.group1 }}'
        
      - uses: tmelliottjr/extract-regex-action@v1.4.0
        id: regex-tags
        with:
          input: ${{ steps.regex-match.outputs.group1 }}
          regex: '(?<=-\s*\[[xX]\]\s+)(.*)'
          flags: 'g'

      - name: Dump tags
        run: |
          echo '${{ steps.regex-tags.outputs.resultString }}'
          echo '${{ steps.regex-tags.outputs.resultArray }}'
