name: Actions Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '\n([\S\s]*)\n\s*\n'

      - name: Dump match
        run: |
          echo '${{ steps.regex-match.outputs.match }}'
          echo '${{ steps.regex-match.outputs.group1 }}'
