name: Actions Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-test-suites
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '.*'
      
      - name: Dump match
        run: |
          echo '${{ steps.regex-test-suites.outputs.match }}'
          echo '${{ steps.regex-test-suites.outputs.group1 }}'
